### ISSUE TITLE
Readiness for piwigo 11

### ISSUE THREAD

**Issue by georg90** [Piwigo/piwigo-tscroller#4]
Hey!
Someone still using this? I think its awesome, but will it work on Piwigo 11 ? I saw many plugins pushing an update.

@modus75 Maybe you can have quick check?

**Comment by git-emil** [comment]
I've disabled it and replaced it with this code:

```
/* loading="lazy" for all thumbnails */
add_event_handler('loc_end_index_thumbnails', 'lazy');
function lazy($tpl_thumbnails_var)
{
	global $template;
	$template->set_prefilter('index_thumbnails', 'lazy_pref');
	return $tpl_thumbnails_var;
}
function lazy_pref($content)
{
	global $page, $template;
	$search = '<img ';
	$content=str_replace($search,'<img loading="lazy" ',$content);
	return $content;
}
```

in my themeconfig.inc.php. 

Works like a charm with modern browsers supporting the loading attribute.

**Comment by georg90** [comment]
@git-emil thanks! this works in lazy loading the pictures.

However using the addon also enables "endless" scrolling through all the images, instead of individual pages.

Still think this addon has value and thinking of porting it if I get the time.

**Comment by tttdevelop** [comment]
@georg90 I also have been a great fan of this plugin for years. You can continue to use this in piwigo 11 and so far I've not had issue with it.

You have to install manually as it is not registered for piwigo 11, so you can't install from the web admin. To do this follow these instructions;

1. Go to your root location of piwigo installation on your server
2. Navigate to the plugins folder - normally www/gallery/plugins/
3. Clone this git

`git clone https://github.com/modus75/piwigo-tscroller`

4. Then go into piwigo web admin and navigate to plugins where you can activate it
5. It will give a warning that the plugin seems to be incompatible. But it will allow you to activate it.

Done !

**Comment by georg90** [comment]
worked! thank you :)
I was afraid of just activating it, so I never just "tried" if it simply works.

Who needs to  bump the compatability piwigo or the plugin? I couldn't find any information about versioning within the plugin.

**Comment by tttdevelop** [comment]
I think it is in the piwigo site extensions page not in the plugin code. It will need to be updated by the original developer or whoever has access to the extension admin. But he hasn't been active here in github since 2018. Not sure if there is a way to contact the team of piwigo to see if they can contact the original developer or add a new extra admin to the extension so it can be updated.
